export interface KeybindInfo {
    name: string
    ctrl: boolean
    meta: boolean
    shift: boolean
}

export type KeybindConfigKey =
    | "quit"
    | "toggle_console"
    | "focus_next"
    | "focus_prev"
    | "focus_panel_1"
    | "focus_panel_2"
    | "focus_panel_3"
    | "focus_panel_4"
    | "nav_down"
    | "nav_up"
    | "nav_page_up"
    | "nav_page_down"
    | "command_palette"
    | "refresh"
    | "enter"
    | "escape"
    | "prev_tab"
    | "next_tab"
    | "jj_new"
    | "jj_new_options"
    | "jj_edit"
    | "jj_describe"
    | "jj_squash"
    | "jj_abandon"
    | "jj_duplicate"
    | "jj_resolve"
    | "jj_undo"
    | "jj_redo"
    | "jj_restore"
    | "jj_rebase"
    | "jj_split"
    | "jj_git_fetch"
    | "jj_git_fetch_all"
    | "jj_git_push"
    | "jj_git_push_all"
    | "bookmark_create"
    | "bookmark_delete"
    | "bookmark_rename"
    | "bookmark_forget"
    | "bookmark_set"
    | "bookmark_move"
    | "bookmark_stack"
    | "bookmark_diff_origin"
    | "bookmark_toggle_remote"
    | "toggle_file_tree"
    | "toggle_diff_formatter"
    | "toggle_diff_style"
    | "toggle_diff_wrap"
    | "diff_scroll_left"
    | "diff_scroll_right"
    | "nav_prev_hunk"
    | "nav_next_hunk"
    | "nav_prev_file"
    | "nav_next_file"
    | "open_recent"
    | "open"
    | "open_direct"
    | "open_editor"
    | "open_editor_all"
    | "toggle_focus_mode"
    | "search"
    | "rebase_descendants"
    | "rebase_branch"
    | "rebase_skip_emptied"
    | "rebase_insert_after"
    | "rebase_insert_before"
    | "squash_destination_message"
    | "squash_keep_emptied"
    | "squash_interactive"
    | "input_nav_down"
    | "input_nav_up"
    | "dialog_confirm"
    | "dialog_cancel"
    | "dialog_back"

export type KeybindConfig = Record<KeybindConfigKey, string>

export const DEFAULT_KEYBINDS: KeybindConfig = {
    quit: "q",
    toggle_console: "§",
    focus_next: "tab",
    focus_prev: "shift+tab",
    focus_panel_1: "1",
    focus_panel_2: "2",
    focus_panel_3: "3",
    focus_panel_4: "4",
    nav_down: "j,down",
    nav_up: "k,up",
    nav_page_up: "ctrl+u",
    nav_page_down: "ctrl+d",
    command_palette: "ctrl+p,?",
    refresh: "ctrl+r",
    enter: "enter",
    escape: "escape",
    prev_tab: "[,h,left",
    next_tab: "],l,right",
    jj_new: "n",
    jj_new_options: "N",
    jj_edit: "e",
    jj_describe: "d",
    jj_squash: "s",
    jj_abandon: "a",
    jj_duplicate: "D",
    jj_resolve: "R",
    jj_undo: "u",
    jj_redo: "U",
    jj_restore: "d",
    jj_rebase: "r",
    jj_split: "S",
    jj_git_fetch: "f",
    jj_git_fetch_all: "F",
    jj_git_push: "p",
    jj_git_push_all: "P",
    bookmark_create: "c",
    bookmark_delete: "d",
    bookmark_rename: "r",
    bookmark_forget: "x",
    bookmark_set: "b",
    bookmark_move: "m",
    bookmark_stack: "s",
    bookmark_diff_origin: "C",
    bookmark_toggle_remote: "R",
    toggle_file_tree: "-",
    toggle_diff_formatter: "-",
    toggle_diff_style: "v",
    toggle_diff_wrap: "w",
    diff_scroll_left: "h,left",
    diff_scroll_right: "l,right",
    nav_prev_hunk: "[",
    nav_next_hunk: "]",
    nav_prev_file: "{",
    nav_next_file: "}",
    open_recent: "ctrl+o",
    open: "o",
    open_direct: "O",
    open_editor: "e",
    open_editor_all: "E",
    toggle_focus_mode: "ctrl+x",
    search: "/",
    rebase_descendants: "s",
    rebase_branch: "b",
    rebase_skip_emptied: "e",
    rebase_insert_after: "shift+a",
    rebase_insert_before: "shift+b",
    squash_destination_message: "u",
    squash_keep_emptied: "shift+k",
    squash_interactive: "i",
    input_nav_down: "down",
    input_nav_up: "up",
    dialog_confirm: "y,enter",
    dialog_cancel: "n,escape",
    dialog_back: "escape",
}
